# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://Louis5228.github.io/deck_of_card/"

git_url = "https://github.com/Louis5228/deck_of_card/tree/master/"

def custom_doc_links(name): return None
